# Generated by Django 5.2.7 on 2025-10-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
